config/routes.rb
Rails.application.routes.draw do

  root to: "twits#index"

  resources :twits
  resources :users, only: [:index]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }, path_names: { sign_in: :login, sign_up: :register, sign_out: :logout}

  devise_scope :user do
    get '/users/logout' => 'users/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twit.rb
class Twit < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twits
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /twits
  # GET /twits.json
  def index
    @twits = Twit.all.order("created_at DESC")
  end

  # GET /twits/1
  # GET /twits/1.json
  def show
  end

  # GET /twits/new
  def new
    @twit = current_user.twits.build
  end

  # GET /twits/1/edit
  def edit
  end

  # POST /twits
  # POST /twits.json
  def create
    @twit = current_user.twits.build(twit_params)

    respond_to do |format|
      if @twit.save
        format.html { redirect_to root_path, notice: 'Twit was successfully created.' }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1
  # PATCH/PUT /twits/1.json
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to root_path, notice: 'Twit was successfully updated.' }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1
  # DELETE /twits/1.json
  def destroy
    @twit.destroy
    respond_to do |format|
      format.html { redirect_to twits_url, notice: 'Twit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twit_params
      params.require(:twit).permit(:body, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(_resource)
    new_user_session_url
  end
end


app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(_resource)
    root_path
  end
end


app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <h3>Welcome <%= current_user.name %> @<%= current_user.username %></h3>
  <p><%= current_user.email %></p>
<%end%>
<%= link_to "Logout", destroy_user_session_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/twits/_form.html.erb
<%= form_with(model: twit, local: true) do |form| %>
  <% if twit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twit.errors.count, "error") %> prohibited this twit from being saved:</h2>

      <ul>
        <% twit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/twits/edit.html.erb
<h1>Editing Twit</h1>

<%= render 'form', twit: @twit %>

<%= link_to 'Show', @twit %> |
<%= link_to 'Back', twits_path %>

app/views/twits/index.html.erb
<% if current_user.nil? %>

  <div>
    <button><%= link_to 'Login', new_user_session_path %></button>
    <button><%= link_to 'Register', new_user_registration_path %></button>
  </div>

<% else %>

  <% if current_user %>
    <p id="notice"><%= notice %></p>

    <div>
      <br>
      <h4 style="display: inline"><%= current_user.name %></h4>
      <p style="display: inline">(@<%= current_user.username %>)</p>
      <button style="display: inline"><%= link_to 'Edit', edit_user_registration_path %></button>
      <button style="display: inline"><%= link_to "Logout", destroy_user_session_path %></button>
    </div>

    <div>
      <br>
      <h3 style="display: inline">Your Twits</h3>
      <button style="display: inline"><%= link_to 'New Twit', new_twit_path %></button>
      <br>
      <br>
    </div>

    <table>
      <thead>
      <tr>
        <th>Body</th>
        <th>Name</th>
        <th>Username</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>

      <% current_user.twits.each do |twit| %>
        <tr>
          <td><%= twit.body %></td>
          <td><%= current_user.name %></td>
          <td><%= current_user.username %></td>
          <td><%= current_user.email %></td>
          <td><button><%= link_to 'Show', twit %></button></td>
          <td><button><%= link_to 'Edit', edit_twit_path(twit) %></button></td>
          <td><button><%= link_to 'Destroy', twit, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        </tr>
      <% end %>

      </tbody>
    </table>

    <hr>

    <% @users = User.all %>
    <% @users.each do |user| %>
      <% user.twits.each do |twit| %>
        <div style="background-color: #999999">
          <h3><%= user.name %><span style="font-weight: normal">@<%= user.username %></span></h3>
          <%= twit.body %>
        </div>
        <br>
        <br>
      <% end %>
    <% end %>

  <% end %>

<% end %>

app/views/twits/new.html.erb
<h1>New Twit</h1>

<%= render 'form', twit: @twit %>

<%= link_to 'Back', twits_path %>

app/views/twits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @twit.body %>
</p>

<p>
  <strong>Username:</strong>
  <%= current_user.username %>
</p>

<p>
  <strong>Nname:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= current_user.email %>
</p>

<%= link_to 'Edit', edit_twit_path(@twit) %> |
<%= link_to 'Back', twits_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>